### ISSUE TITLE
Help wanted: create a Wasm example/tutorial using rust_xlsxwriter

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/rust_xlsxwriter#38]
### Help wanted

It would be great if someone could create a Wasm example/tutorial using `rust_xlsxwriter`.

Ideally I could add this as a section in or link from the [Working with the rust_xlsxwriter library](https://rustxlsxwriter.github.io/index.html) user guide. 

An example like one in the [SheetJS](https://docs.sheetjs.com/docs/getting-started/example) tutorial would be good but don't copy it exactly.

It would be good to use the `write_row_matrix()` or `write_column_matrix()` methods that are currently on main (#16) and which will be in v0.39.0.

It would also be nice to use whatever is the current Rust/Wasm best practices.

**Comment by robothot** [comment]
@jmcnamara  I am a novice in rust, can I try to do this work?

**Comment by jmcnamara** [comment]
On Fri, 12 May 2023 at 10:21, 苯苯 ***@***.***> wrote:

> @jmcnamara <https://github.com/jmcnamara> I am a novice in rust, can I
> try to do this work?
>

Sure. Some volunteer is better than no volunteer.

**Comment by robothot** [comment]
@jmcnamara  Any plans?  For example 

1. Create a project, or create a folder on this project ?
2. Documentation site is using [docusaurus](https://github.com/facebook/docusaurus) or [dumi](https://github.com/umijs/dumi)

I think we or maybe need some planning ?

**Comment by jmcnamara** [comment]
> Any plans?

I think the best approach would be to create a separate GitHub project and get some examples working with Javascript.

Then, once it it working, and we get some user testing/feedback, I will add a chapter in the `rust_xlsxwriter` [User Guide ](https://rustxlsxwriter.github.io/index.html) with links/code from the Wasm project.

**Comment by Ashci42** [comment]
Hey, was working on a rust lib with python and wasm bindings and noticed this issue. In my case, I couldn't get `rust_xlswriter` to work with wasm because of time not being implement on that platform (yet). I believe this is due to your usage of the `chrono` crate. It looks like they have a `wasmbind` feature flag that should make it work in WebAssembly ([for reference](https://github.com/chronotope/chrono/issues/382)).

 Could the feature flag be added for chrono?

**Comment by jmcnamara** [comment]
Could the feature flag be added for chrono?

@Ashci42 I have made `chrono` an "optional on" feature in `rust_xlsxwriter` v0.41.0 and it will be "optional off" in future version (and current main). I've added the [`ExcelDateTime`](https://docs.rs/rust_xlsxwriter/latest/rust_xlsxwriter/struct.ExcelDateTime.html) struct as a native alternative.

**Comment by jmcnamara** [comment]
> I don't think it is currently possible to run `rust_xlsxwriter` with Wasm.

Thanks for taking a look at this.



> Calling `Workbook::new()` calls `DocProperties::new()`, which itself calls [`ExcelDateTime::utc_now()`](https://github.com/jmcnamara/rust_xlsxwriter/blob/c3bd9d8c375f32f5f10151397f25f3ec7905b9b6/src/datetime.rs#L1177). This method calls [`std::time::SystemTime::now()`](https://doc.rust-lang.org/std/time/struct.SystemTime.html#method.now), which panics on runtime in Wasm.

Excel has metadata with a creation and modification data (which are the same for a new file). It is possible to specify a datetime so that `ExcelDateTime::utc_now()` isn't called like this:

```rust
use rust_xlsxwriter::{DocProperties, ExcelDateTime, Workbook, XlsxError};

fn main() -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    // Create a file creation date for the file.
    let date = ExcelDateTime::from_ymd(2023, 1, 1)?;

    // Add it to the document metadata.
    let properties = DocProperties::new().set_creation_datetime(&date);
    workbook.set_properties(&properties);

    let worksheet = workbook.add_worksheet();
    worksheet.write_string(0, 0, "Hello")?;

    workbook.save("properties.xlsx")?;

    Ok(())
}
```

See: https://rustxlsxwriter.github.io/workbook/checksum.html#checksum-of-a-saved-file

However, I don't know if it is still incompatible with Wasm if the `ExcelDateTime::utc_now()` function is still in the compile path even if not in the execution path.




> I also think that packager::assemble_file will probably panic, as it calls [`std::thread::(scope::)spawn`](https://github.com/jmcnamara/rust_xlsxwriter/blob/c3bd9d8c375f32f5f10151397f25f3ec7905b9b6/src/packager.rs#L115), which I don't think is implemented in Wasm.

That was only added in recently in v0.44.0. You could test with version v0.43.0 instead. If required I could put it behind a `wasm` feature flag.

**Comment by jmcnamara** [comment]
> It is possible to specify a datetime so that `ExcelDateTime::utc_now()` isn't called like this:

Actually I'm wrong. It is called at the creation of `DocProperties`. However, I could make that an `Option<>`.

**Comment by Clipi-12** [comment]
I have forked the repo ([here](https://github.com/Clipi-12/rust_xlsxwriter)) changing those two things (making `DocsProperties.creation_time` an Option and putting `std::thread::spawn` under a cfg attribute) and everything seems to work so far. I'm afraid that I don't have a ___simple___ example to show that it actually works, though.

> It might matter to some folks if the creation time isn't actually the creation time.
Yeah, that makes sense. Although maybe a `DocProperties::new_lazy` method could be added so that `DocProperties::new` does what it does now (plus wrapping `DocsProperties.creation_time` in `Some`), and therefore we have both methods without an additional feature flag

**Comment by jmcnamara** [comment]
> I have forked the repo ([here](https://github.com/Clipi-12/rust_xlsxwriter)) changing those two things (making `DocsProperties.creation_time` an Option and putting `std::thread::spawn` under a cfg attribute) and everything seems to work so far.

Thanks for that. 

For the `ExcelDateTime::utc_now()` issue I think a more complete solution would be to fall back to a JS function on wasm targets like Chrono does. I could implement a `wasmbind` feature flag like Chrono and pass it to Chrono when that is in use. (I now see that this is what @Ashci42 was asking for above but I missed the point.) I'll also use it to make `ExcelDateTime` JS compliant and to turn off the back end threading.



> I'm afraid that I don't have a _**simple**_ example to show that it actually works, though.

That is still the main help I need here. It doesn't have to be full tutorial, like I asked for above. Even a hello world example with some instructions would be useful to debug and test issues like this.

**Comment by jmcnamara** [comment]
@Clipi-12 (or @Ashci42) I have pushed a (hopefully) Wasm compatible version to the `wasm` branch if you can test it.

I don't know if it also needs some `target_arch` configs. You can let me know.

I need to add a support for the `wasm` flag into the `chrono` flag as well. I'll add that a bit later.

**Comment by Clipi-12** [comment]
I'll take a look at this.  
In the meanwhile, it could be important to think about Wasm in non-javascript environments. I'm not an expert on this, but I know Wasm was ["designed to be capable of being executed without a Javascript VM present"](https://webassembly.org/docs/non-web/#:~:text=WebAssembly%20is%20also%20being%20designed%20to%20be%20capable%20of%20being%20executed%20without%20a%20JavaScript%20VM%20present).  
Also, if we look at [chrono's `Utc::now()` implementation](https://github.com/chronotope/chrono/blob/bc410bb054932518822eb393147aad939862c7a5/src/offset/utc.rs#L63-L87) they don't call `js_sys` unless they absolutely need to (i.e. when wasm32-unknown-unknown is used). In the case that wasi or emscriptem are used, chrono doesn't use js_sys or anything javascript-related, (presumably) so that the Wasm code doesn't need a javascript environment.

**Comment by jmcnamara** [comment]
> Also, if we look at [chrono's `Utc::now()` implementation](https://github.com/chronotope/chrono/blob/bc410bb054932518822eb393147aad939862c7a5/src/offset/utc.rs#L63-L87) they don't call `js_sys` unless they absolutely need to

Yes, you are probably right. I had a look at the `time.rs` crate and they do the same thing. I'll update the branch.

**Comment by Clipi-12** [comment]
I have made a minimal example of a rust_xlsxwriter program that compiles to WASM:
https://github.com/Clipi-12/rust_xlsx_wasm_example
It can be used to compile and test in a browser environment, in Nodejs, in Deno, and in WASI.

It is a bit big, but there's not much I can do, since most files are just there to replace std::fs with browser-specific/nodejs-specific/deno-specific code that does the same thing.

I also found a bug in the current branch. [You are taking the result of Date.now() as if it meant seconds since UNIX_EPOCH](https://github.com/jmcnamara/rust_xlsxwriter/commit/b0c2a687b2af48bf9d04414c9b855d8016e0e0d5#diff-dea6b5915f4569219169086434bf0bf034579033e1bef4d94529210fd1ee73d7R1201-R1210), while it actually represents the number of milliseconds since UNIX_EPOCH (so you just have to divide it by 1,000 and it would be fixed)

**Comment by jmcnamara** [comment]
That is really great. Thanks!

I was able to get the browser example working with minimal fuss. That and the other environments make it perfect for testing so that is just what I needed.


> I also found a bug in the current branch

I fixed that on the `wasm` branch and force pushed it.

**Comment by jmcnamara** [comment]
> It can be used to compile and test in a browser environment, in Nodejs, in Deno, and in WASI.

I was able to get all of the targets (Browser, Node.js, Deno and WASI) working after installing a few dependencies. So that is really useful for testing.





> It is a bit big, but there's not much I can do, since most files are just there to replace std::fs with browser-specific/nodejs-specific/deno-specific code that does the same thing.

It doesn't seem too bad.

I have a few minor suggestions. I'll make them directly on your repo a bit later.

Thanks once more.

**Comment by jmcnamara** [comment]
@Clipi-12 I added support in `rust_xlsxwriter` for wrapping `wasm_bindgen::JsValue` into `XlsxError`. That should simplify the code and make handling errors in the wasm app(s) easier since it already wraps `IO::Error`. 

I've pushed it to a different branch (`wasm2`) since it doesn't work for wasmtime which gives a generic and not very clear error:

```bash
$ wasmtime --dir=. pkg/wasi/rust_xlsx_wasm_example.wasm
Error: failed to run main module `pkg/wasi/rust_xlsx_wasm_example.wasm`

Caused by:
    0: failed to instantiate "pkg/wasi/rust_xlsx_wasm_example.wasm"
    1: unknown import: `__wbindgen_placeholder__::__wbindgen_throw` has not been defined

```

**Comment by Clipi-12** [comment]
Maybe you forgot to `git add` something, or maybe I'm not understanding correctly, but all I can see in the last commit is a mapping [from `XlsxError` to `JsValue`](https://github.com/jmcnamara/rust_xlsxwriter/commit/40e5d98c6a55ba4fe7ff82c66c5ae82a3ed0cee3#diff-97e25e2a0e41c578875856e97b659be2719a65227c104b992e3144efa000c35eR303-R314), not the other way around

**Comment by Clipi-12** [comment]
@jmcnamara I modified a private copy of the wasm2 branch and got rid of the error by simply avoiding to import wasm-bindgen in wasi. Honestly I think the best option is to rename the `wasm` feature to `javascript`, since wasi already does all the thing we are trying to do with wasi natively.

Well, everything but std::thread:spawn, which doesn't really need the feature anyways, since it can use `#[cfg(target_arch = "wasm32")]`

**Comment by jmcnamara** [comment]
> never mind, I understand what you meant with the last commit. It is indeed very useful! I'll probably remove some code in the example thanks to that

That is good. I meant to attach the updated example but somehow failed to do it, but it looks like you figured it out anyway. :-) I'll have a look at the changes a bit later. 

Apologies for slow responses, I have some other things going on at the moment.

**Comment by jmcnamara** [comment]
I got a chance to look at this again and your recent changes look good. I've cleaned things up on my side and merged the changes onto main. I'll push the changes to crates.io in the next few days if everything is okay on your side and mine.



> Honestly I think the best option is to rename the `wasm` feature to `javascript`,

I'm going to stick with `wasm` for now since I think that makes most sense in terms of what what users will be looking for.



> Well, everything but `std::thread:spawn`, which doesn't really need the feature-flag check anyways, since it can use `#[cfg(target_arch = "wasm32")]`

Good point. I made that change.



> Also, an additional benefit is that if we rename the feature flag to `javascript` we don't have to do the long check

I don't really get this. Could you explain a bit more.

**Comment by Clipi-12** [comment]
> I don't really get this. Could you explain a bit more. Or submit a PR against main with the suggested changes.

I was about to submit a PR when I noticed that it actually doesn't matter. I thought that we could ignore the `target_arch` and `target_os` as long as the `wasm` feature flag was set because of the panicking we faced when running in non-javascript targets. I thought that we could assume we were in a js environment because otherwise it would still panic elsewhere.

However, the panic no longer occurs, and even if it did, it's honestly more safe to just do the check, in case it would ever get solved (which it already is).

**Comment by jmcnamara** [comment]
Thank for that @Clipi-12 

I've pushed the changes to crates.io in v0.47.0.

I've mentioned your repo in the release notes: https://rustxlsxwriter.github.io/changelog.html#0470---2023-09-02

Thanks once more for the help. There will probably be some improvements to be added over time (in both repos) but this is a good start.

I'm going to close this feature request since I think it completes the "Help needed" request.

**Comment by henrikekblad** [comment]
How do I build the library as a wasm exposing all functions to the javascript side?  I would like to dynalically build the excel file using javascript. 
The example-wasm-project only seem to expose the start-method which builds an static excel-file.

**Comment by jmcnamara** [comment]
> How do I build the library as a wasm exposing all functions to the javascript side (for the web)? I would like to dynamically build the excel file using javascript.

The work in this thread was mainly to ensure that `rust_xlsxwriter` could/would work with wasm. As you point out there aren't any mappings to other API functions. Someone will need to build that using `wasm_bindgen` or similar.  @henrikekblad  or @Clipi-12 would either of you be interested in building that. If not I could open another "help wanted" request to see if anyone volunteers.

**Comment by henrikekblad** [comment]
Thanks for a quick reply. I might not be the right person to create the bindings as this was the first time I have ever tried compiling a rust-project.

A bit of background for my request. I've incorporated the [excelize-wasm ](https://github.com/xuri/excelize-wasm) project in my web frontend to generate out excel-fles. But the wasm file becomes about 15MB uncompressed and is very slow for large files. As excelize is written i go I suspect it becomes much larger than a rust-based exporter would be.

**Comment by jmcnamara** [comment]
@henrikekblad Just to close out on this: you will probably need to stick with the golang version for now. There isn't comparable functionality in the `rust_xlsxwriter` wasm support, for now.

**Comment by henrikekblad** [comment]
Ok, thanks anyway! I'll keep an eye on your project for future updates.

**Comment by jmcnamara** [comment]
See also the `wasm-xlsxwriter` project: https://github.com/estie-inc/wasm-xlsxwriter

**Comment by henrikekblad** [comment]
Wow, great! I'll test it immidiately.

**Comment by henrikekblad** [comment]
A little performace comparison between ExcelizeWasm and wasm-xmlwriter. Quite impressive! Ping @jmcnamara, @tamaroning. In the test I export 1500 rows / 14 columns.  Processing-time was calculated after wasm was loaded, on average for 3 runs.

|           | ExcelizeWasm           | wasm-xmlwriter  |
| ------------- |:-------------:| -----:|
| Wasm footprint (uncompressed, Mb)    | 12.9  | 1.27  |
| Processing time (s)   |     6.18   |   0.17 |

I was unforunately unable to do any meaningful memory consumption tests in the browser. My conclusion: Rust seems to be way faster and have a much less footprint than Wasm-go projects.

**Comment by jmcnamara** [comment]
@henrikekblad Thanks for the performance data. That is impressive. It would be interesting to see a similar result with 15,000 rows by 14 columns if you are able to test that.

See also this recent performance comparison: https://github.com/jmcnamara/rust_xlsxwriter/issues/1#issuecomment-2474796507 where excelize.go and rust_xlsxwriter are similar in performance (outside of wasm).

**Comment by henrikekblad** [comment]
22000 rows / 13 cols

xlswriter: 2.44s
excelize: 105.13s

**Comment by jmcnamara** [comment]
Wow. Thanks for that.
